def update(input_file_path, output_file_path, variable_name):
    with open(input_file_path, 'rb') as f:
        bts = f.read()
    with open(output_file_path, 'w') as o:
        o.write("// this file is auomatically generated by update_resources.py\n")
        o.write(f"const unsigned char {variable_name} [{len(bts)}] = ")
        o.write("{\n    ")

        o.write(','.join([str(x) for x in bts]))

        o.write("\n};")

from pathlib import Path
import zipfile
release_apk = Path("Projects/Android/HeartBeatNative/nativeblereader/build/outputs/apk/release/nativeblereader-release-unsigned.apk")
if release_apk.exists():
    print("release apk exists, use it")
    with zipfile.ZipFile(release_apk) as apk:
        data = apk.read("classes.dex")
        with open("extra/HeartBeatBLEReader.dex", "wb") as f:
            f.write(data)
update("extra/HeartBeatBLEReader.dex", "src\\HeartBeatBLEDex.inl", "ble_dex")