#ifndef V
#define V(key)
#endif
V(enabled)

V(heart_config)
V(heart_devices)
V(heart_senders)
V(heart_osc_senders)
V(hyperate)
V(pulsoid)

V(hyperate_reset)
V(hyperate_save_and_connect)
V(hyperate_input_hint)
V(no_message_from_server)

V(hyperate_con_start)
V(hyperate_network_error)
V(hyperate_retry)
V(hyperate_connected)
V(hyperate_no_id)
V(hyperate_refused)
V(hyperate_you_have_message)

V(pulsoid_no_token)

V(unsupported_feature_udpatre_mod)

V(heart_osc_port)

V(scan_start)
V(scan_stop)
V(turn_location_on)

V(scaning)
V(auto_scaning)
V(no_scan)

V(ble_none_selected)
V(ble_none_not_selected)


V(ble_permission_unknown)
V(ble_permission_needed)
V(ble_permission_paired_only)

V(pairing)
V(not_pairing)
V(hiding_mac_addr)
V(showing_mac_addr)
V(server_skip)
V(heart_rate_lan_protocol_ver)
V(mod_version)
V(for_game)
V(no_beatleader)
V(waiting)

V(config_adjust_speed)

V(text_color)
V(flash_text_color)
V(replay_flash_text_color)
V(flash_duration_when_text_come)
V(flash_test)

V(line_space)
V(reset_default_line_space)

V(reset_to_default)

V(data_source)

V(data_source_random)
V(data_source_lan)
V(data_source_bluetooth)
V(data_source_osc)
V(data_source_hyperate)
V(data_source_pulsoid)

V(enable_record)
V(record_dev_name)

V(age)

V(select_ui)
V(max_heart)

V(pulsoid_reconnect)
V(pulsoid_input_hint)
V(pulsoid_edit_config_hint)
V(pulsoid_connect)
V(pulsoid_done)
V(pulsoid_cancel)
V(pulsoid_token)
V(pulsoid_clear_token)

V(your_setthings_is_in_another_menu)

V(ui_not_avaliable_in_qounter)
V(ignore_qounters)
V(ignore_qounters_hint)

V(advance_ui_required)

V(mdns_enable)
V(mdns_name_no)
V(mdns_name_title)
