"""
MIT LICENSE

Asset embbed script, by frto027

Usage for qpm projects:

1. put this script on scripts/build_assets.py
2. put the following things in your CMakeLists.txt

################# begin of asset generate ####################

file(GLOB_RECURSE ASSET_FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/assets/*
)
file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/assets_hpp)
file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/assets_cpp)
set(ASSET_HPP   ${CMAKE_CURRENT_BINARY_DIR}/assets_hpp/asset.hpp)
set(ASSET_CPP   ${CMAKE_CURRENT_BINARY_DIR}/assets_cpp/asset.cpp)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
add_custom_command(
        OUTPUT ${ASSET_HPP} ${ASSET_CPP}
        COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/scripts/build_assets.py ${ASSET_HPP} ${ASSET_CPP}
        DEPENDS ${ASSET_FILES}
        COMMENT "Generating Assets"
        VERBATIM
)
add_custom_target(generate_assets DEPENDS ${ASSET_HPP} ${ASSET_CPP})
add_dependencies(${COMPILE_ID} generate_assets)
target_sources(${COMPILE_ID} PRIVATE ${ASSET_CPP})
target_include_directories(${COMPILE_ID} PRIVATE ${CMAKE_CURRENT_BINARY_DIR}/assets_hpp)

################# end of asset generate ####################

3. make a folder /assets, put some file inside it
4. in your code, use the following:

#include "asset.hpp"
uint8_t * some_pointer = AssetGenerated::your_asset_png;
size_t some_pointer_size = sizeof(AssetGenerated::your_asset_png);

"""

from pathlib import Path
import sys
import re
asset_folder = Path(__file__).parent.parent / 'assets'

assert asset_folder.exists(), "You need an asset folder in '/assets'"

assert len(sys.argv) == 3, "Usage: python3 scripts/build_assets.py <output.hpp> <output.cpp>"

file_filter_re = re.compile("[^a-zA-Z0-9]")

hpp_file = [f"/* auto-generated by {Path(sys.argv[0]).name} */\n\n"]
cpp_file = []

hpp_file.append("""#include <stdint.h>

namespace AssetGenerated{
""")

for asset in asset_folder.glob("*"):
    if asset.name.startswith("."):
        continue
    name = asset.name
    name = file_filter_re.sub("_", name)


    if len(name) == 0 or name[0].isdigit():
        name = "_" + name
    with asset.open("rb") as f:
        bts = f.read()
    
    print(f"building asset AssetGenerated::{name}[{len(bts)}]")

    hpp_file.append(f"    extern const uint8_t {name}[{len(bts)}];\n")

    cpp_file.append(f"const uint8_t AssetGenerated::{name}[{len(bts)}]=")
    cpp_file.append("\n    {")
    cpp_file.append(','.join([str(x) for x in bts]))
    cpp_file.append("}\n;\n")
hpp_file.append("}")

hpp_file_str = ''.join(hpp_file)
cpp_file_str = ''.join(cpp_file)

def write_file_if_changed(file_path:str, file_content:str):
    if Path(file_path).exists():
        with open(file_path, 'r') as f:
            if f.read() == file_content:
                return
    with open(file_path, 'w') as f:
        f.write(file_content)

write_file_if_changed(sys.argv[1], f"#pragma once\n\n{hpp_file_str}")
write_file_if_changed(sys.argv[2], f"{hpp_file_str}\n\n{cpp_file_str}")